metadata:
  owner: shotat
  name: ghrc
spec:
  repo:
    description: I'm awesome!!!
    homepage: ""
    private: false
    topics:
    - go
    - github
    allowRebaseMerge: false
    allowSquashMerge: true
    allowMergeCommit: null
  labels:
    - name: "bug :bug:"
      description: "Small bug fix required"
      color: "b01f26"
    - name: "skip_ci"
      description: ""
      color: "000000"
    - name: duplicate
      color: "123456"
  protections:
  - branch: master
    requiredStatusChecks:
      strict: true
      contexts: []
    enforceAdmins: false
    requiredPullRequestReviews: null
    restrictions: null
