metadata:
  owner: shotat
  name: ghrc
spec:
  repo:
    description: GHRC is a tool for managing GitHub Repository Configurations in a
      declarative way.
    homepage: ""
    private: false
    allowSquashMerge: true
    allowMergeCommit: false
    allowRebaseMerge: false
    topics:
    - cli
    - git
    - github
    - go
    - infrastructure-as-code
  labels:
  - name: bug
    description: Something isn't working
    color: d73a4a
  - name: documentation
    description: Improvements or additions to documentation
    color: 0075ca
  - name: question
    description: Further information is requested
    color: d876e3
  - name: review
    description: ""
    color: ffffff
  protections:
  - branch: master
    requiredStatusChecks:
      strict: false
      contexts: []
    enforceAdmins: true
    requiredPullRequestReviews:
      dismissalRestrictions:
        users: []
        teams: []
      dismissStaleReviews: false
      requireCodeOwnerReviews: false
      requiredApprovingReviewCount: 1
    restrictions:
      users: []
      teams: []

