metadata:
  owner: shotat
  name: ghrc
spec:
  description: I'm awesome!!!
  homepage: ""
  private: false
  topics:
    - go
    - github
  labels:
    - name: "bug :bug:"
      description: "Small bug fix required"
      color: "b01f26"
    - name: "skip_ci"
      description: ""
      color: "000000"
  allowRebaseMerge: false
  allowSquashMerge: true
  allowMergeCommit: null
  protections:
  - branch: master
    requiredStatusChecks:
      strict: true
      contexts: []
    enforceAdmins: false
    requiredPullRequestReviews: null
    restrictions: null
